const Geometries = [
  {
    name: "AnonymousAnamankaNODE",
    position: [0, 0, 0],
    file: "models/AnonymousAnamonkaNODE.gltf",
    title: "Anonymous Anamanka",
    description: "This is an anonymous anamanka!",
    color_base: "#D8ACB7",
    color_clicked: "#D78499",
    color_grey: "#F7F3F3",
    project_link: "https://en.wikipedia.org/wiki/Architecture",
    strings: [
      {
        name: "AnonymousAnamankaSTRINGS",
        file: "models/AnonymousAnamankaSTRINGS.gltf",
      },
    ],
  },
  {
    name: "ConjectureSpeculationNODE",
    position: [0, 0, 0],
    file: "models/ConjectureSpeculationNODE.gltf",
    title: "Conjecture Speculation",
    image: "images/Conjecture.jpg",
    description: "This is a cat!",
    color_base: "#C29375",
    color_clicked: "#BE6B37",
    color_grey: "#F7F3F3",
    project_link: "https://en.wikipedia.org/wiki/Architecture",
    strings: [
      {
        name: "ConjectureSpeculationSTRINGS",
        file: "models/ConjectureSpeculationSTRINGS.gltf",
      },
    ],
  },
  {
    name: "MenstrationNODE",
    position: [0, 0, 0],
    file: "models/MenstrationNODE.gltf",
    title: "Menstration",
    description: "This is a cat!",
    color_base: "#EFB9A4",
    color_clicked: "#FF9970",
    color_grey: "#F7F3F3",
    project_link: "https://en.wikipedia.org/wiki/Architecture",
    strings: [
      {
        name: "MenstrationSTRINGS",
        file: "models/MenstrationSTRINGS.gltf",
      },
    ],
  },
  {
    name: "MeralEkinciogluNODE",
    position: [0, 0, 0],
    file: "models/MeralEkinciogluNODE.gltf",
    title: "Meral Ekincioglu",
    description: "This is a cat!",
    color_base: "#ED9B96",
    color_clicked: "#FF645C",
    color_grey: "#F7F3F3",
    project_link: "https://en.wikipedia.org/wiki/Architecture",
    strings: [
      {
        name: "MeralEkinciogluSTRINGS",
        file: "models/MeralEkinciogluSTRINGS.gltf",
      },
    ],
  },
  {
    name: "StitchNODE",
    position: [0, 0, 0],
    file: "models/StitchNODE.gltf",
    title: "Stitch",
    description: "This is a cat!",
    color_base: "#E9BAB9",
    color_clicked: "#F09593",
    color_grey: "#F7F3F3",
    project_link: "https://en.wikipedia.org/wiki/Architecture",
    strings: [
      {
        name: "SitchSTRINGS",
        file: "models/SitchSTRINGS.gltf",
      },
    ],
  },
  {
    name: "TodaysDilemaNODE",
    position: [0, 0, -1000],
    file: "models/TodaysDilemaNODE.gltf",
    title: "Today's Dilemma",
    image: "images/TodaysDilemma.jpg",
    description: "This is a cat!",
    color_base: "#D8ABBE",
    color_clicked: "#D981A5",
    color_grey: "#F7F3F3",
    project_link: "https://en.wikipedia.org/wiki/Architecture",
    strings: [
      {
        name: "TodaysDilemaSTRINGS",
        file: "models/TodaysDilemaSTRINGS.gltf",
      },
    ],
  },
  {
    name: "UmbrellaMomentsNODE",
    position: [0, 0, 0],
    file: "models/UmbrellaMomentsNODE.gltf",
    title: "Umbrella Moments",
    image: "images/UmbrellaMoments.jpg",
    description: "This is a cat!",
    color_base: "#DDABA6",
    color_clicked: "#E28279",
    color_grey: "#F7F3F3",
    project_link: "https://en.wikipedia.org/wiki/Architecture",
    strings: [
      {
        name: "UmbrellaMomentsSTRINGS",
        file: "models/UmbrellaMomentsSTRINGS.gltf",
      },
    ],
  },
  {
    name: "VirginiaNODE",
    position: [0, 0, 0],
    file: "models/VirginiaNODE.gltf",
    title: "Virginia",
    description: "This is a cat!",
    color_base: "#E9AABD",
    color_clicked: "#F47B9F",
    color_grey: "#F7F3F3",
    project_link: "https://en.wikipedia.org/wiki/Architecture",
    strings: [
      {
        name: "VirginiaSTRINGS",
        file: "models/VirginiaSTRINGS.gltf",
      },
    ],
  },
  {
    name: "waiNODE",
    position: [0, 0, 0],
    file: "models/waiNODE.gltf",
    title: "wai",
    description: "This is a cat!",
    color_base: "#E1B097",
    color_clicked: "#EC8E5E",
    color_grey: "#F7F3F3",
    project_link: "https://en.wikipedia.org/wiki/Architecture",
    strings: [
      {
        name: "waiSTRINGS",
        file: "models/waiSTRINGS.gltf",
      },
    ],
  },
];

export default Geometries;
